version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      -echo Insatlling dependencies...
      - npm install

pre_build:
  commands:
    - echo Nothing to do in pre_build phase...
    - ls -l

build:
  commands:
    - echo Build started on `date`
    - npm run build
    - ls -l
post_build:
  commands:
    - echo Build completed on `date`

artifacts:
  files:
    - dist/shop/*
    - dist/shop/assets/*
